### ISSUE TITLE
Styles for larger screens on home page don't match existing site

### ISSUE THREAD

**Issue by ealtunyay** [DavidVerghese/PhilipAyers#5]

**Comment by DavidVerghese** [comment]
I have made the front page mostly responsive. I still need to fix the spacing of the pictures in the 'most-viewed' div.

**Comment by DavidVerghese** [comment]
I wasn't able to figure out to make the 'most-viewed' div responsive with CSS grid. I was able to make it responsive by getting rid of the CSS grid styling and using flex box to position the pictures instead.
